Repository Hi-lingual/Hilingual-Android, pull requests merged in 2025-08, with the labels that each got.

#186 [MOD/#185] 디자인 시스템 컬러 추가 및 변경
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualBasicBottomSheet.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/theme/Color.kt
Labels: MOD✅, 🍀큰나현

#189 [MOD#188] 디자인 변경 대응
  presentation/auth/src/main/java/com/hilingual/presentation/auth/component/GoogleSignButton.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/calendar/CalendarHeader.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/calendar/DayItem.kt
  presentation/home/src/main/res/drawable/ic_arrow_down_28.xml
  presentation/home/src/main/res/drawable/ic_arrow_left_28.xml
  presentation/home/src/main/res/drawable/ic_arrow_right_28.xml
  presentation/home/src/main/res/drawable/ic_filled_bubble_34.xml
Labels: MOD✅, 🍀민재

#187 [MOD/#184] 일기 상세 디자인 수정사항 반영
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/DiaryViewModeToggle.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/tab/GrammarSpellingScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/tab/RecommendExpressionScreen.kt
Labels: MOD✅, 🍀작은나현

#203 [CHORE/#194] Proguard/R8 Setting
  app/proguard-rules.pro
  core/common/consumer-rules.pro
  core/common/proguard-rules.pro
  core/designsystem/consumer-rules.pro
  core/designsystem/proguard-rules.pro
  core/localstorage/consumer-rules.pro
  core/localstorage/proguard-rules.pro
  core/navigation/consumer-rules.pro
  core/navigation/proguard-rules.pro
  core/network/build.gradle.kts
  core/network/consumer-rules.pro
  core/network/proguard-rules.pro
  data/auth/consumer-rules.pro
  data/auth/proguard-rules.pro
  data/calendar/consumer-rules.pro
  data/calendar/proguard-rules.pro
  data/diary/consumer-rules.pro
  data/diary/proguard-rules.pro
  data/user/consumer-rules.pro
  data/user/proguard-rules.pro
  data/voca/consumer-rules.pro
  data/voca/proguard-rules.pro
  presentation/auth/consumer-rules.pro
  presentation/auth/proguard-rules.pro
  presentation/community/consumer-rules.pro
  presentation/community/proguard-rules.pro
  presentation/diaryfeedback/consumer-rules.pro
  presentation/diaryfeedback/proguard-rules.pro
  presentation/diarywrite/consumer-rules.pro
  presentation/diarywrite/proguard-rules.pro
  presentation/home/consumer-rules.pro
  presentation/home/proguard-rules.pro
  presentation/main/consumer-rules.pro
  presentation/main/proguard-rules.pro
  presentation/mypage/consumer-rules.pro
  presentation/mypage/proguard-rules.pro
  presentation/onboarding/consumer-rules.pro
  presentation/onboarding/proguard-rules.pro
  presentation/splash/consumer-rules.pro
  presentation/voca/consumer-rules.pro
  presentation/voca/proguard-rules.pro
Labels: CHORE🧹, 🍀민재

#213 [FEAT/#212] OTP 에러메세지 및 다이얼로그 추가와 소소한 개선
  presentation/otp/src/main/java/com/hilingual/presentation/otp/OtpScreen.kt
Labels: FEAT✨, MOD✅, 🍀민재

#227 [MOD/#226] 프로필 이미지 공통 컴포넌트 구현 및 적용
  core/common/src/main/java/com/hilingual/core/common/constant/UrlConstant.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/picker/ProfileImagePicker.kt
  core/designsystem/src/main/res/drawable/ic_camera_20.xml
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingScreen.kt
  presentation/onboarding/src/main/res/drawable/ic_onboarding_camera_32.xml
  presentation/otp/src/main/java/com/hilingual/presentation/otp/OtpScreen.kt
Labels: MOD✅, 🍀민재

#238 [FEAT/#222] 일기 게시/비공개/삭제 다이얼로그 추가
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/diary/DiaryDeleteDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/diary/DiaryPublishDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/diary/DiaryUnpublishDialog.kt
Labels: FEAT✨, 🍀작은나현

#218 [MOD/#193] GUI 추가로 인한 TabRow, ToggleSwitch 공통 컴포넌트 이동
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/tabrow/HilingualBasicTabRow.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/toggle/HilingualBasicToggleSwitch.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/DiaryViewModeToggle.kt
Labels: CHORE🧹, MOD✅, 🍀작은나현

#235 [FEAT/#228] 팔로우 관련 공통 컴포넌트 작업
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/button/UserActionButton.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/UserActionItem.kt
Labels: FEAT✨, 🍀큰나현, 🍀작은나현

#240 [FEAT/#237] 1차 스프린트 온보딩 UI 변경 대응
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingScreen.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingViewModel.kt
Labels: FEAT✨, 🍀민재

#259 [ADD/#258] HilingualMenuBottomSheetItem 파라미터에 텍스트, 아이콘 색상 추가
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualMenuBottomSheet.kt
Labels: ADD💜, 🍀작은나현

#254 [CHORE/#253] 일기 상세 리소스 중앙화
  core/designsystem/src/main/res/drawable/chip_feedback_card_ai.xml
  core/designsystem/src/main/res/drawable/chip_feedback_card_me.xml
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/FeedbackCard.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/FeedbackReportBottomSheet.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/RecommendExpressionCard.kt
  presentation/diaryfeedback/src/main/res/drawable/ic_report_24.xml
  presentation/diaryfeedback/src/main/res/drawable/ic_save_saved_28.xml
  presentation/diaryfeedback/src/main/res/drawable/ic_save_unsaved_28.xml
Labels: CHORE🧹, 🍀작은나현

#250 [FIX/#223] 바텀시트 dismiss 이슈 수정
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualBasicBottomSheet.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualMenuBottomSheet.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualYearMonthPickerBottomSheet.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/FeedbackReportBottomSheet.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/calendar/HilingualCalendar.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/component/TermsBottomSheet.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaBottomSheet.kt
Labels: FEAT✨, 🍀작은나현

#239 [FEAT/#229] 피드 관련 공통 컴포넌트 구현
  core/common/src/main/java/com/hilingual/core/common/util/FormatRelativeTime.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/FeedCard.kt
Labels: FEAT✨, 🍀큰나현

#256 [MOD/#252] 단어장 뷰 로딩 범위 및 리소스 경로 수정
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaBottomSheet.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaCard.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaDialog.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaInfo.kt
  presentation/voca/src/main/res/drawable/ic_az_24.xml
  presentation/voca/src/main/res/drawable/ic_check_24.xml
  presentation/voca/src/main/res/drawable/ic_list_24.xml
  presentation/voca/src/main/res/drawable/ic_listdown_24.xml
  presentation/voca/src/main/res/drawable/ic_save_28_empty.xml
  presentation/voca/src/main/res/drawable/ic_save_28_filled.xml
  presentation/voca/src/main/res/drawable/ic_save_36_empty.xml
  presentation/voca/src/main/res/drawable/ic_save_36_filled.xml
Labels: MOD✅, 🍀큰나현

#274 [FEAT/#271] Add Notification components
  gradle/libs.versions.toml
  presentation/notification/.gitignore
  presentation/notification/build.gradle.kts
  presentation/notification/src/main/AndroidManifest.xml
  presentation/notification/src/main/java/com/hilingual/presentation/notification/component/NotificationDetailContent.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/component/NotificationItem.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/component/NotificationSwitchItem.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/component/NotificationTapRow.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/component/NotificationTopAppBar.kt
  settings.gradle.kts
Labels: FEAT✨, 🍀민재

#282 [REF/#279] 시스템 바(Status Bar) 처리 방식 리팩토링
  build-logic/src/main/java/com/hilingual/build_logic/ComposeAndroid.kt
  build-logic/src/main/java/hilingual.android.feature.gradle.kts
  core/common/src/main/java/com/hilingual/core/common/extension/ModfierExt.kt
  core/common/src/main/java/com/hilingual/core/common/provider/SystemBarsColor.kt
  gradle/libs.versions.toml
  presentation/auth/src/main/java/com/hilingual/presentation/auth/AuthScreen.kt
  presentation/community/src/main/java/com/hilingual/presentation/community/CommunityScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/main/build.gradle.kts
  presentation/main/src/main/java/com/hilingual/presentation/main/MainActivity.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingScreen.kt
  presentation/splash/src/main/java/com/hilingual/presentation/splash/SplashScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
Labels: REFACTOR🧽, 🍀민재

#286 [FIX/#285] MainScreen의 스낵바 클릭 핸들러 로직 개선
  .run/Hilingual [spotlessApply].run.xml
  app/build.gradle.kts
  core/common/src/main/java/com/hilingual/core/common/constant/UrlConstant.kt
  core/common/src/main/java/com/hilingual/core/common/extension/ContextExt.kt
  core/common/src/main/java/com/hilingual/core/common/model/SnackbarRequest.kt
  core/common/src/main/java/com/hilingual/core/common/trigger/LocalSnackbarTrigger.kt
  core/common/src/main/java/com/hilingual/core/common/trigger/LocalToastTrigger.kt
  core/common/src/main/java/com/hilingual/core/common/util/FormatRelativeTime.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualImagePickerBottomSheet.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualMenuBottomSheet.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/button/UserActionButton.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/FeedCard.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/UserActionItem.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/diary/DiaryDeleteDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/diary/DiaryPublishDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/diary/DiaryUnpublishDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dropdown/HilingualBasicDropdownMenu.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/picker/ProfileImagePicker.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/snackbar/DiarySnackbar.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/tabrow/HilingualBasicTabRow.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/toggle/HilingualBasicToggleSwitch.kt
  data/user/src/main/java/com/hilingual/data/user/model/NicknameValidationResult.kt
  presentation/community/src/main/java/com/hilingual/presentation/community/CommunityViewModel.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/FeedbackReportBottomSheet.kt
  presentation/feedprofile/build.gradle.kts
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/component/BlockBottomSheet.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/component/FeedEmptyCard.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/component/FeedProfileDropDownMenu.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/component/FeedProfileInfo.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/component/FeedUserActionButton.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/component/ReportBlockBottomSheet.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/HomeDropDownMenu.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/util/DateUtil.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/detail/NotificationDetailScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/detail/component/NotificationDetailContent.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationMainScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/component/EmptyImage.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/component/NotificationItem.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/component/NotificationTapRow.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/component/NotificationTopAppBar.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/model/FeedNotificationItemModel.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/model/NoticeNotificationItemModel.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/tab/FeedScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/tab/NoticeScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/setting/NotificationSettingScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/setting/component/NotificationSwitchItem.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/component/TermsBottomSheet.kt
Labels: FIX🪲, 🍀민재

#294 [FEAT/#291] 피드 검색 UI 및 로직 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/button/UserActionButton.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualBasicTextField.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualSearchTextField.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualShortTextField.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/component/FeedSearchHeader.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/component/SearchEmptyCard.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/model/UserSearchUiModel.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/search/FeedSearchScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/search/FeedSearchUiState.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/search/FeedSearchViewModel.kt
Labels: FEAT✨, 🍀작은나현

#293 [FEAT/#281] 피드 프로필 및 팔로우 화면 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/FeedCard.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedTabScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/component/FeedProfileInfo.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListUiState.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListViewModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/component/FollowTabRow.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/model/FollowItemModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/DiaryListScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileUiState.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileViewModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/BlockBottomSheet.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/FeedEmptyCard.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/FeedProfileDropDownMenu.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/FeedProfileInfo.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/FeedProfileTabRow.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/FeedUserActionButton.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/ReportBlockBottomSheet.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/model/DiaryItemModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/model/FeedProfileInfoModel.kt
Labels: FEAT✨, 🍀큰나현

#296 [FEAT/#287] 마이페이지 화면 UI 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/topappbar/TitleLeftAlignedTopAppBar.kt
  core/designsystem/src/main/res/drawable/ic_image_24.xml
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/BlockedUserScreen.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/BlockedUserUiState.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/MypageNavigation.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/MypageScreen.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/ProfileEditScreen.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/component/WithdrawDialog.kt
Labels: FEAT✨, 🍀지영

#311 [CHORE] 프로젝트 아이콘을 추가합니다
  .gitignore
  .idea/icon.svg
Labels: CHORE🧹, 🍀민재

#313 [FIX/#312] 피드 프로필 및 팔로우 화면 엠티뷰 수정
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/DiaryListScreen.kt
Labels: FIX🪲, 🍀큰나현

#303 [FEAT/#301] 피드 프로필, 팔로우 관련 네비게이션 연결
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/navigation/FeedNavigation.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/search/FeedSearchViewModel.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryScreen.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryUiState.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/model/ProfileContentUiModel.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/navigation/FeedDiaryNavigation.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListUiState.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListViewModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileUiState.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileViewModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/FeedProfileInfo.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/navigation/FeedProfileNavigation.kt
  presentation/main/build.gradle.kts
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/state/MainAppState.kt
Labels: FEAT✨, 🍀큰나현

#306 [FEAT/#302] 마이페이지 뷰모델, 네비게이션 연결
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainTab.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/state/MainAppState.kt
  presentation/mypage/build.gradle.kts
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/MyPageScreen.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/MyPageUiState.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/MyPageViewModel.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/MypageNavigation.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/blockeduser/BlockedUserScreen.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/blockeduser/BlockedUserUiModel.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/blockeduser/BlockedUserUiState.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/blockeduser/BlockedUserViewModel.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/navigation/MyPageNavigation.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/profileedit/ProfileEditScreen.kt
Labels: FEAT✨, 🍀지영

#316 [FEAT/#275] 알림 모듈 네비게이션 세팅
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeUiState.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/navigation/HomeNavigation.kt
  presentation/main/build.gradle.kts
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/state/MainAppState.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/detail/NotificationDetailScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/detail/NotificationDetailUiState.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/detail/NotificationDetailViewModel.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationMainScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationMainUiState.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationMainViewModel.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/navigation/NotificationNavigation.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/setting/NotificationSettingScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/setting/NotificationSettingUiState.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/setting/NotificationSettingViewModel.kt
Labels: FEAT✨, 🍀민재

#319 [ADD/#318] 피드 메뉴 드롭다운 연결
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/FeedCard.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dropdown/HilingualBasicDropdownMenu.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedTabScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedUiState.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/model/FeedListItemUiModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/DiaryListScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/FeedProfileDropDownMenu.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/model/DiaryItemModel.kt
Labels: ADD💜, MOD✅, 🍀큰나현, 🍀작은나현
