Repository Hi-lingual/Hilingual-Android, pull requests merged in 2025-07, with the labels that each got.

#7 [FEAT/#3] 디자인 시스템 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/theme/Type.kt
  core/designsystem/src/main/res/font/suit_bold.otf
  core/designsystem/src/main/res/font/suit_medium.otf
  core/designsystem/src/main/res/font/suit_regular.otf
  core/designsystem/src/main/res/font/suit_semibold.otf
Labels: FEAT✨, 🍀큰나현

#5 [FEAT/#4] 네트워크 모듈 세팅
  core/network/build.gradle.kts
  core/network/src/main/java/com/hilingual/core/network/AuthInterceptor.kt
  core/network/src/main/java/com/hilingual/core/network/BaseResponse.kt
  core/network/src/main/java/com/hilingual/core/network/HeaderConstants.kt
  core/network/src/main/java/com/hilingual/core/network/JsonStringExt.kt
  core/network/src/main/java/com/hilingual/core/network/NetworkModule.kt
  core/network/src/main/java/com/hilingual/core/network/Qualifiers.kt
  core/network/src/main/java/com/hilingual/core/network/TokenAuthenticator.kt
Labels: FEAT✨, 🍀민재

#8 [FEAT/#6] 코어 모듈 및 기본 세팅 추가
  app/src/main/res/values/themes.xml
  build-logic/src/main/java/hilingual.android.data.gradle.kts
  core/common/src/main/java/com/hilingual/core/common/extension/ModfierExt.kt
  core/common/src/main/java/com/hilingual/core/common/extension/RunCatchingExt.kt
  core/common/src/main/java/com/hilingual/core/common/util/SuspendRunCatching.kt
  core/common/src/main/java/com/hilingual/core/common/util/UiState.kt
  core/navigation/src/main/java/com/hilingual/core/navigation/MainTabRoute.kt
  core/navigation/src/main/java/com/hilingual/core/navigation/Route.kt
Labels: FEAT✨, 🍀민재

#14 [FEAT/#11] Coil 래퍼 컴포넌트 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/image/NetworkImage.kt
  core/designsystem/src/main/res/drawable/ic_default_image.png
Labels: FEAT✨, 🍀민재

#17 [FEAT/#9] BottomBar UI 및 기본 네비게이션 세팅
  core/navigation/build.gradle.kts
  core/navigation/src/main/java/com/hilingual/core/navigation/MainTabRoute.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/navigation/HomeNavigation.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainActivity.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainNavigator.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainTab.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/component/MainBottomBar.kt
  presentation/main/src/main/res/drawable/ic_book_24.xml
  presentation/main/src/main/res/drawable/ic_community_24.xml
  presentation/main/src/main/res/drawable/ic_home_24.xml
  presentation/main/src/main/res/drawable/ic_my_24.xml
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/navigation/VocaNavigation.kt
Labels: FEAT✨, 🍀작은나현

#23 [FEAT/#15] 공통 컴포넌트 Button 구현
  core/common/src/main/java/com/hilingual/core/common/extension/ModfierExt.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/button/HilingualButton.kt
Labels: FEAT✨, 🍀큰나현

#27 [FEAT/#26] HomeHeader 구현
  presentation/home/src/main/java/com/hilingual/presentation/home/component/HomeHeader.kt
  presentation/home/src/main/res/drawable/ic_bubble_16.xml
  presentation/home/src/main/res/drawable/ic_fire_16.xml
Labels: FEAT✨, 🍀민재

#31 [FEAT/#19] BottomSheet 컴포넌트 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualBasicBottomSheet.kt
Labels: FEAT✨, 🍀작은나현

#32 [FEAT/#24] Dialog 디자인 시스템 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/button/DialogButton.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/HilingualBasicDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/OneButtonDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/TwoButtonDialog.kt
Labels: FEAT✨, 🍀큰나현

#35 [FEAT/#28] Home Footer Components 만들엇서요
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryDateInfo.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryEmptyCard.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryPreviewCard.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryTimeInfo.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/TodayTopic.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/WriteDiaryButton.kt
  presentation/home/src/main/res/drawable/ic_plus_16.xml
  presentation/home/src/main/res/drawable/ic_time_16.xml
  presentation/home/src/main/res/drawable/ic_transfer_28.xml
  presentation/home/src/main/res/drawable/img_diary_empty.png
  presentation/home/src/main/res/drawable/img_diary_lock.png
Labels: FEAT✨, 🍀민재

#37 [Feat/#20] DatePicker 바텀시트 구현
  core/common/src/main/java/com/hilingual/core/common/extension/ModfierExt.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/bottomsheet/HilingualYearMonthPickerBottomSheet.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/datapicker/HilingualBasicPicker.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/datapicker/HilingualYearMonthPicker.kt
Labels: FEAT✨, 🍀작은나현

#41 [REFACTOR/#40] diaryfeedback 빌드 로직 적용
  presentation/diaryfeedback/build.gradle.kts
Labels: REFACTOR🧽, 🍀작은나현

#44 [FEAT/#36] 홈(캘린더) UI 완성했어요
  build-logic/src/main/java/hilingual.android.feature.gradle.kts
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/image/NetworkImage.kt
  core/designsystem/src/main/res/drawable/ic_default_image.png
  core/designsystem/src/main/res/drawable/img_default_image.png
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeUiState.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/HomeHeader.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/calendar/CalendarHeader.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/calendar/HilingualCalendar.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryEmptyCard.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryPreviewCard.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/navigation/HomeNavigation.kt
  presentation/home/src/main/res/drawable/img_diary_empty.png
  presentation/home/src/main/res/drawable/img_diary_lock.png
  presentation/main/src/main/AndroidManifest.xml
Labels: FEAT✨, 🍀민재

#49 [FEAT/#42] 일기 상세 헤더 구현
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/DiaryFeedbackTabRow.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/tab/GrammarSpellingScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/tab/RecommendExpressionScreen.kt
Labels: FEAT✨, 🍀작은나현

#57 [FEAT/#55] 단어장 뷰 헤더 구현
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaHeader.kt
Labels: FEAT✨, 🍀큰나현

#59 [FEAT/#53] statusBarColor를 지정할 수 있는 컴포넌트를 만들어요
  core/common/src/main/java/com/hilingual/core/common/provider/SystemBarsColor.kt
  presentation/auth/src/main/java/com/hilingual/presentation/auth/AuthScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainActivity.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
Labels: FEAT✨, 🍀효빈

#63 [FEAT/#60] 하이링 서버 로그인 연결 및 토큰 관리 로직 구현햇삼
  app/build.gradle.kts
  core/localstorage/src/main/java/com/hilingual/core/localstorage/TokenManager.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/TokenManagerImpl.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/di/LocalStorageModule.kt
  core/network/src/main/java/com/hilingual/core/network/AuthInterceptor.kt
  core/network/src/main/java/com/hilingual/core/network/HeaderConstants.kt
  core/network/src/main/java/com/hilingual/core/network/NetworkModule.kt
  core/network/src/main/java/com/hilingual/core/network/Qualifiers.kt
  core/network/src/main/java/com/hilingual/core/network/TokenAuthenticator.kt
  core/network/src/main/java/com/hilingual/core/network/service/TokenRefreshService.kt
  data/auth/build.gradle.kts
  data/auth/src/main/java/com/hilingual/data/auth/datasource/AuthApiDataSource.kt
  data/auth/src/main/java/com/hilingual/data/auth/datasource/GoogleAuthDataSource.kt
  data/auth/src/main/java/com/hilingual/data/auth/datasourceimpl/AuthRemoteDataSourceImpl.kt
  data/auth/src/main/java/com/hilingual/data/auth/datasourceimpl/GoogleAuthDataSourceImpl.kt
  data/auth/src/main/java/com/hilingual/data/auth/di/AuthManagerModule.kt
  data/auth/src/main/java/com/hilingual/data/auth/di/DataSourceModule.kt
  data/auth/src/main/java/com/hilingual/data/auth/di/ServiceModule.kt
  data/auth/src/main/java/com/hilingual/data/auth/di/TokenRefreshServiceModule.kt
  data/auth/src/main/java/com/hilingual/data/auth/dto/request/LoginRequestDto.kt
  data/auth/src/main/java/com/hilingual/data/auth/dto/response/LoginResponseDto.kt
  data/auth/src/main/java/com/hilingual/data/auth/dto/response/ReissueTokenResponseDto.kt
  data/auth/src/main/java/com/hilingual/data/auth/model/LoginModel.kt
  data/auth/src/main/java/com/hilingual/data/auth/repository/AuthRepository.kt
  data/auth/src/main/java/com/hilingual/data/auth/repositoryimpl/AuthRepositoryImpl.kt
  data/auth/src/main/java/com/hilingual/data/auth/service/LoginService.kt
  data/auth/src/main/java/com/hilingual/data/auth/service/ReissueService.kt
  data/auth/src/main/java/com/hilingual/data/auth/service/TokenRefreshServiceImpl.kt
  presentation/auth/src/main/java/com/hilingual/presentation/auth/AuthScreen.kt
  presentation/auth/src/main/java/com/hilingual/presentation/auth/AuthViewModel.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainNavigator.kt
Labels: FEAT✨, 🍀민재

#68 [FEAT/#67] Lottie 컴포넌트 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/image/HilingualLottieImage.kt
Labels: FEAT✨, 🍀민재

#77 [FEAT/#71] 단어장 뷰 조립
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualSearchTextField.kt
  presentation/auth/src/main/java/com/hilingual/presentation/auth/AuthScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaUiState.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaViewModel.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaBottomSheet.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaEmptyCard.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaHeader.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaInfo.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/model/VocaGroup.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/model/VocaItem.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/model/VocaItemDetail.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/navigation/VocaNavigation.kt
  presentation/voca/src/main/res/drawable/ic_az_24.xml
  presentation/voca/src/main/res/drawable/ic_check_24.xml
  presentation/voca/src/main/res/drawable/ic_listdown_24.xml
Labels: FEAT✨, 🍀큰나현

#79 [FEAT/#72] 일기 작성하기 화면 UI 구현
  core/common/src/main/java/com/hilingual/core/common/extension/ModfierExt.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/TwoButtonDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualLongTextField.kt
  presentation/diarywrite/build.gradle.kts
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/component/DiaryWriteCancelDialog.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/component/ImageSelectBottomSheet.kt
  presentation/diarywrite/src/main/res/drawable/ic_camera_24.xml
  presentation/diarywrite/src/main/res/drawable/ic_gallary_24.xml
Labels: FEAT✨, 🍀지영

#81 [FEAT/#80] 원본 이미지 확인 화면 UI 구현
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/PhotoDetailModal.kt
Labels: FEAT✨, 🍀작은나현

#88 [FEAT/#84] 일기 상세 네비게이션 연결
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/ModalImage.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/DiaryCard.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/navigation/DiaryFeedbackNavigation.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/tab/GrammarSpellingScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/navigation/HomeNavigation.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainNavigator.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
Labels: FEAT✨, 🍀작은나현

#98 [FEAT/#94] 일기 작성하기 화면 사진 선택 btn 클릭 시 갤러리로 연결되도록 기능 구현
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteUiState.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/component/PhotoSelectButton.kt
Labels: FEAT✨, 🍀지영

#99 [FEAT/#93] 캘린더 구현완료
  core/common/src/main/java/com/hilingual/core/common/extension/StateFlowExt.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/button/HilingualButton.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/datasouceimpl/CalendarRemoteDataSourceImpl.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/datasource/CalendarRemoteDataSource.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/di/DataSourceModule.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/di/RepositoryModule.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/di/ServiceModule.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/dto/response/CalendarResponseDto.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/dto/response/DiaryThumbnailResponseDto.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/dto/response/TopicResponseDto.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/model/CalendarModel.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/model/DiaryThumbnailModel.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/model/TopicModel.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/repository/CalendarRepository.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/repositoryimpl/CalendarRepositoryImpl.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/service/CalendarService.kt
  data/user/src/main/java/com/hilingual/data/user/datasouceimpl/UserRemoteDataSourceImpl.kt
  data/user/src/main/java/com/hilingual/data/user/datasource/UserRemoteDataSource.kt
  data/user/src/main/java/com/hilingual/data/user/dto/reponse/UserInfoResponseDto.kt
  data/user/src/main/java/com/hilingual/data/user/model/UserInfoModel.kt
  data/user/src/main/java/com/hilingual/data/user/model/UserProfileModel.kt
  data/user/src/main/java/com/hilingual/data/user/repository/UserRepository.kt
  data/user/src/main/java/com/hilingual/data/user/repositoryimpl/UserRepositoryImpl.kt
  data/user/src/main/java/com/hilingual/data/user/service/UserService.kt
  presentation/home/build.gradle.kts
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeUiState.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryDateInfo.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/model/DateUiModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/model/DiaryThumbnailUiModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/model/TodayTopicUiModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/model/UserProfileUiModel.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingViewModel.kt
Labels: FEAT✨, 🍀민재

#101 [FEAT/#100] 네트워크 오류 감지 및 다이얼로그 구현
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/HIlingualErrorDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/OneButtonDialog.kt
  core/designsystem/src/main/res/drawable/img_error.png
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainViewModel.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/monitor/NetworkMonitor.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/monitor/NetworkMonitorImpl.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/monitor/NetworkMonitorModule.kt
Labels: FEAT✨, 🍀민재

#103 [FEAT/#102] 디폴트 에러 다이얼로그 프로바이더 구현
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dialog/HIlingualErrorDialog.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/event/DialogController.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/event/LocalDialogController.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingScreen.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingViewModel.kt
Labels: FEAT✨, 🍀민재

#105 [FEAT/#89] 단어장 뷰 api 연결
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualBasicTextField.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualSearchTextField.kt
  data/diary/src/main/java/com/hilingual/data/diary/datasource/DiaryRemoteDataSource.kt
  data/diary/src/main/java/com/hilingual/data/diary/datasourceimpl/DiaryRemoteRemoteDataSourceImpl.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/DataSourceModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/RepositoryModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/ServiceModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/dto/request/BookmarkRequestDto.kt
  data/diary/src/main/java/com/hilingual/data/diary/dto/response/DiaryContentResponseDto.kt
  data/diary/src/main/java/com/hilingual/data/diary/dto/response/DiaryFeedbackResponseDto.kt
  data/diary/src/main/java/com/hilingual/data/diary/dto/response/DiaryRecommendExpressionResponseDto.kt
  data/diary/src/main/java/com/hilingual/data/diary/model/DiaryFeedbackModel.kt
  data/diary/src/main/java/com/hilingual/data/diary/model/DiaryModel.kt
  data/diary/src/main/java/com/hilingual/data/diary/model/DiaryRecommendExpressionModel.kt
  data/diary/src/main/java/com/hilingual/data/diary/model/PhraseBookmarkModel.kt
  data/diary/src/main/java/com/hilingual/data/diary/repository/DiaryRepository.kt
  data/diary/src/main/java/com/hilingual/data/diary/repositoryimpl/DiaryRepositoryImpl.kt
  data/diary/src/main/java/com/hilingual/data/diary/service/DiaryService.kt
  data/voca/src/main/java/com/hilingual/data/voca/datasource/VocaDataSource.kt
  data/voca/src/main/java/com/hilingual/data/voca/datasourceimpl/VocaDataSourceImpl.kt
  data/voca/src/main/java/com/hilingual/data/voca/di/DataSourceModule.kt
  data/voca/src/main/java/com/hilingual/data/voca/di/RepositoryModule.kt
  data/voca/src/main/java/com/hilingual/data/voca/di/ServiceModule.kt
  data/voca/src/main/java/com/hilingual/data/voca/dto/response/VocaDetailResponseDto.kt
  data/voca/src/main/java/com/hilingual/data/voca/dto/response/VocaGroupResponseDto.kt
  data/voca/src/main/java/com/hilingual/data/voca/dto/response/VocaItemResponseDto.kt
  data/voca/src/main/java/com/hilingual/data/voca/dto/response/VocaListResponseDto.kt
  data/voca/src/main/java/com/hilingual/data/voca/model/VocaDetailModel.kt
  data/voca/src/main/java/com/hilingual/data/voca/model/VocaListModel.kt
  data/voca/src/main/java/com/hilingual/data/voca/repository/VocaRepository.kt
  data/voca/src/main/java/com/hilingual/data/voca/repositoryimpl/VocaRepositoryImpl.kt
  data/voca/src/main/java/com/hilingual/data/voca/service/VocaService.kt
  presentation/diaryfeedback/build.gradle.kts
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackUiState.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackViewModel.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/model/DiaryContentUiModel.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/model/FeedbackContentUiModel.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/model/RecommendExpressionUiModel.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/tab/GrammarSpellingScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/tab/RecommendExpressionScreen.kt
  presentation/voca/build.gradle.kts
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaUiState.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaViewModel.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaInfo.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaModal.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/model/VocaGroup.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/model/VocaItem.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/model/VocaItemDetail.kt
Labels: FEAT✨, 🍀큰나현

#112 [MOD/#111] 이미지 로드 에러 처리 추가
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/image/NetworkImage.kt
  core/designsystem/src/main/res/drawable/img_load_fail_large.png
  core/designsystem/src/main/res/drawable/img_load_fail_small.png
Labels: MOD✅, 🍀민재

#115 [ADD/#114] 키스토어 추가
  .gitignore
  app/build.gradle.kts
  core/network/build.gradle.kts
  keystore/hi-lingual-debug-key.jks
  keystore/hi-lingual-release-key.jks
Labels: ADD💜, 🍀효빈

#122 [MOD/#119] 자동 로그인 수정 및 QA용 주석 설정 및 프로필 이미지 변경ㅋ
  core/localstorage/src/main/java/com/hilingual/core/localstorage/TokenManager.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/TokenManagerImpl.kt
  core/network/src/main/java/com/hilingual/core/network/TokenAuthenticator.kt
  data/auth/src/main/java/com/hilingual/data/auth/repositoryimpl/AuthRepositoryImpl.kt
  data/auth/src/main/java/com/hilingual/data/auth/service/TokenRefreshServiceImpl.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/component/DiaryCard.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/HomeHeader.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryDateInfo.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/splash/src/main/java/com/hilingual/presentation/splash/SplashScreen.kt
  presentation/splash/src/main/java/com/hilingual/presentation/splash/SplashViewModel.kt
  presentation/splash/src/main/java/com/hilingual/presentation/splash/navigation/SplashNavigation.kt
Labels: MOD✅, 🍀민재

#124 [HOTFIX/#123] signingConfig 오류 해결햇서요
  app/build.gradle.kts
  keystore/hi-lingual-release-key.jks
Labels: HOTFIX🧯, 🍀효빈

#129 [FEAT/#118] 일기 작성하기 일기 피드백 요청 POST 서버 및 네비게이션 연결
  core/network/src/main/java/com/hilingual/core/network/ContentUriRequestBody.kt
  core/network/src/main/java/com/hilingual/core/network/NetworkModule.kt
  data/diary/build.gradle.kts
  data/diary/src/main/java/com/hilingual/data/diary/datasource/DiaryRemoteDataSource.kt
  data/diary/src/main/java/com/hilingual/data/diary/datasourceimpl/DiaryRemoteDataSourceImpl.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/ContentResolverModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/DataSourceModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/dto/response/DiaryFeedbackCreateResponseDto.kt
  data/diary/src/main/java/com/hilingual/data/diary/model/DiaryFeedbackCreateModel.kt
  data/diary/src/main/java/com/hilingual/data/diary/repository/DiaryRepository.kt
  data/diary/src/main/java/com/hilingual/data/diary/repositoryimpl/DiaryRepositoryImpl.kt
  data/diary/src/main/java/com/hilingual/data/diary/service/DiaryService.kt
  presentation/diarywrite/build.gradle.kts
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryFeedbackStatusScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteViewModel.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/component/DiaryFeedbackState.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/component/FeedbackCompleteContent.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/navigation/DiaryWriteNavigation.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
Labels: FEAT✨, 🍀지영

#136 [Fix/#130] 1차 QA 수정
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualBasicTextField.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualLongTextField.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualSearchTextField.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualShortTextField.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/TokenManager.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/TokenManagerImpl.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeUiState.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainNavigator.kt
  presentation/main/src/main/res/drawable/ic_book_24.xml
  presentation/main/src/main/res/drawable/ic_community_24.xml
  presentation/main/src/main/res/drawable/ic_home_24.xml
  presentation/main/src/main/res/drawable/ic_my_24.xml
  presentation/onboarding/build.gradle.kts
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingScreen.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingViewModel.kt
Labels: FIX🪲, 🍀민재

#140 [REF/#137] 멀티파트 통신관련 리펙했습니다.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualBasicTextField.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualSearchTextField.kt
  core/network/src/main/java/com/hilingual/core/network/ContentUriRequestBody.kt
  core/network/src/main/java/com/hilingual/core/network/NetworkModule.kt
  core/network/src/main/java/com/hilingual/core/network/Qualifiers.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/ContentResolverModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/DataSourceModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/RepositoryModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/di/ServiceModule.kt
  data/diary/src/main/java/com/hilingual/data/diary/repositoryimpl/DiaryRepositoryImpl.kt
Labels: FEAT✨, 🍀민재

#146 [DOCS/#144] 리드미 수정
  README.md
Labels: DOCS📗, 🍀효빈

#151 [FEAT/#150] 커뮤니티,마이페이지 모듈 및 임시 뷰 만들었어요
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualSearchTextField.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/img_prototype.png
  core/navigation/src/main/java/com/hilingual/core/navigation/MainTabRoute.kt
  presentation/community/.gitignore
  presentation/community/build.gradle.kts
  presentation/community/consumer-rules.pro
  presentation/community/proguard-rules.pro
  presentation/community/src/main/AndroidManifest.xml
  presentation/community/src/main/java/com/hilingual/presentation/community/CommunityNavigation.kt
  presentation/community/src/main/java/com/hilingual/presentation/community/CommunityScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/navigation/DiaryFeedbackNavigation.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryDateInfo.kt
  presentation/main/build.gradle.kts
  presentation/main/src/main/java/com/hilingual/presentation/main/MainNavigator.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainTab.kt
  presentation/mypage/.gitignore
  presentation/mypage/build.gradle.kts
  presentation/mypage/consumer-rules.pro
  presentation/mypage/proguard-rules.pro
  presentation/mypage/src/main/AndroidManifest.xml
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/MypageNavigation.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/MypageScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaViewModel.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaHeader.kt
  settings.gradle.kts
Labels: FEAT✨, 🍀민재

#158 [DOCS/#157] 의존성 그래프 마커 추가
  README.md
  build.gradle.kts
Labels: DOCS📗, 🍀민재

#166 [FIX/165] 그래프 자동화 삭제
  .github/workflows/update_dependency_graph.yml
  README.md
  gradle/projectDependencyGraph.gradle.kts
  graph/project.dot.png
Labels: FIX🪲, 🍀민재

#170 [MOD/#169] Centralize SharedTransitionScope using CompositionLocal
  core/designsystem/src/main/java/com/hilingual/core/designsystem/event/LocalSharedTransitionScope.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/theme/Theme.kt
  presentation/auth/src/main/java/com/hilingual/presentation/auth/AuthScreen.kt
  presentation/auth/src/main/java/com/hilingual/presentation/auth/navigation/AuthNavigation.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/splash/src/main/java/com/hilingual/presentation/splash/SplashScreen.kt
  presentation/splash/src/main/java/com/hilingual/presentation/splash/navigation/SplashNavigation.kt
Labels: MOD✅, 🍀민재

#177 [DEL/#171] keystore 삭제 및 변경
  .gitignore
  app/build.gradle.kts
  data/auth/src/main/java/com/hilingual/data/auth/datasourceimpl/GoogleAuthDataSourceImpl.kt
  keystore/hi-lingual-debug-key.jks
  keystore/hi-lingual-release-key.jks
Labels: DELETE➖, 🍀민재
