Repository Hi-lingual/Hilingual-Android, pull requests merged in 2025-09, with the labels that each got.

#329 [FIX/#328] 디자인 QA사항 + 딥링크 미사용 변경
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/dropdown/HilingualBasicDropdownMenu.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/HomeDropDownMenu.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationMainUiState.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationMainViewModel.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationUiState.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationViewModel.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/model/FeedNotificationItemModel.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/tab/FeedScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/navigation/NotificationNavigation.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/component/TermsBottomSheet.kt
Labels: FIX🪲, 🍀민재

#331 [MOD/#330] 로그인 서버 연결
  core/localstorage/src/main/java/com/hilingual/core/localstorage/TokenManager.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/TokenManagerImpl.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/UserInfoManager.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/UserInfoManagerImpl.kt
  core/localstorage/src/main/java/com/hilingual/core/localstorage/di/LocalStorageModule.kt
  core/network/src/main/java/com/hilingual/core/network/TokenAuthenticator.kt
  data/auth/build.gradle.kts
  data/auth/src/main/java/com/hilingual/data/auth/datasource/AuthRemoteDataSource.kt
  data/auth/src/main/java/com/hilingual/data/auth/datasourceimpl/AuthRemoteDataSourceImpl.kt
  data/auth/src/main/java/com/hilingual/data/auth/dto/request/LoginRequestDto.kt
  data/auth/src/main/java/com/hilingual/data/auth/dto/response/LoginResponseDto.kt
  data/auth/src/main/java/com/hilingual/data/auth/model/LoginModel.kt
  data/auth/src/main/java/com/hilingual/data/auth/repository/AuthRepository.kt
  data/auth/src/main/java/com/hilingual/data/auth/repositoryimpl/AuthRepositoryImpl.kt
  data/auth/src/main/java/com/hilingual/data/auth/service/TokenRefreshServiceImpl.kt
  data/user/src/main/java/com/hilingual/data/user/repository/UserRepository.kt
  data/user/src/main/java/com/hilingual/data/user/repositoryimpl/UserRepositoryImpl.kt
  presentation/auth/build.gradle.kts
  presentation/auth/src/main/java/com/hilingual/presentation/auth/AuthViewModel.kt
  presentation/onboarding/build.gradle.kts
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingViewModel.kt
  presentation/splash/build.gradle.kts
  presentation/splash/src/main/java/com/hilingual/presentation/splash/SplashViewModel.kt
Labels: MOD✅, REFACTOR🧽, 🍀민재

#322 [FEAT/#309] 피드 홈, 일기, 검색 로직 구현
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedTabScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedUiState.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedViewModel.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/search/FeedSearchViewModel.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryScreen.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryViewModel.kt
Labels: ADD💜, FEAT✨, 🍀작은나현

#334 [FEAT/#332] Connect Authentication Code API and Handle Client ID Branching
  .github/workflows/pr_checker.yml
  data/auth/build.gradle.kts
  data/auth/src/main/java/com/hilingual/data/auth/datasource/AuthRemoteDataSource.kt
  data/auth/src/main/java/com/hilingual/data/auth/datasourceimpl/AuthRemoteDataSourceImpl.kt
  data/auth/src/main/java/com/hilingual/data/auth/di/ServiceModule.kt
  data/auth/src/main/java/com/hilingual/data/auth/dto/request/VerifyCodeRequestDto.kt
  data/auth/src/main/java/com/hilingual/data/auth/repository/AuthRepository.kt
  data/auth/src/main/java/com/hilingual/data/auth/repositoryimpl/AuthRepositoryImpl.kt
  data/auth/src/main/java/com/hilingual/data/auth/service/VerifyService.kt
  presentation/otp/build.gradle.kts
  presentation/otp/src/main/java/com/hilingual/presentation/otp/OtpScreen.kt
  presentation/otp/src/main/java/com/hilingual/presentation/otp/OtpUiState.kt
  presentation/otp/src/main/java/com/hilingual/presentation/otp/OtpViewModel.kt
Labels: FEAT✨, 🍀민재

#333 [FIX/#323] 피드 GUI QA 이슈 해결
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/diary/DiaryCard.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/component/FeedSearchHeader.kt
  presentation/feeddiary/build.gradle.kts
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryScreen.kt
Labels: FIX🪲, 🍀작은나현

#338 [FEAT/#337] Update Home (Calendar) API Handling
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/datapicker/HilingualYearMonthPicker.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/dto/response/DiaryThumbnailResponseDto.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/model/DiaryThumbnailModel.kt
  data/calendar/src/main/java/com/hilingual/data/calendar/service/CalendarService.kt
  data/user/src/main/java/com/hilingual/data/user/dto/reponse/UserInfoResponseDto.kt
  data/user/src/main/java/com/hilingual/data/user/model/UserInfoModel.kt
  data/user/src/main/java/com/hilingual/data/user/service/UserService.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/HomeHeader.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/calendar/HilingualCalendar.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/TodayTopic.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/model/DiaryThumbnailUiModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/model/UserProfileUiModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/navigation/HomeNavigation.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/state/MainAppState.kt
Labels: FEAT✨, MOD✅, 🍀민재

#346 [FEAT/#343] 스프린트 ver 일기 API 연동
  core/designsystem/src/main/java/com/hilingual/core/designsystem/model/DiaryContent.kt
  data/diary/src/main/java/com/hilingual/data/diary/datasource/DiaryRemoteDataSource.kt
  data/diary/src/main/java/com/hilingual/data/diary/datasourceimpl/DiaryRemoteDataSourceImpl.kt
  data/diary/src/main/java/com/hilingual/data/diary/dto/response/DiaryContentResponseDto.kt
  data/diary/src/main/java/com/hilingual/data/diary/model/BookmarkResult.kt
  data/diary/src/main/java/com/hilingual/data/diary/model/DiaryModel.kt
  data/diary/src/main/java/com/hilingual/data/diary/repository/DiaryRepository.kt
  data/diary/src/main/java/com/hilingual/data/diary/repositoryimpl/DiaryRepositoryImpl.kt
  data/diary/src/main/java/com/hilingual/data/diary/service/DiaryService.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackUiState.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackViewModel.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/navigation/DiaryFeedbackNavigation.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/state/MainAppState.kt
Labels: FEAT✨, 🍀작은나현

#352 [ADD/#349] 피드 data 모듈 기본 통신 구조 세팅
  data/feed/src/main/java/com/hilingual/data/feed/datasource/FeedRemoteDataSource.kt
  data/feed/src/main/java/com/hilingual/data/feed/datasourceimpl/FeedRemoteDataSourceImpl.kt
  data/feed/src/main/java/com/hilingual/data/feed/di/DataSourceModule.kt
  data/feed/src/main/java/com/hilingual/data/feed/di/RepositoryModule.kt
  data/feed/src/main/java/com/hilingual/data/feed/di/ServiceModule.kt
  data/feed/src/main/java/com/hilingual/data/feed/repository/FeedRepository.kt
  data/feed/src/main/java/com/hilingual/data/feed/repositoryimpl/FeedRepositoryImpl.kt
  data/feed/src/main/java/com/hilingual/data/feed/service/FeedService.kt
  settings.gradle.kts
Labels: ADD💜, 🍀작은나현

#369 [FEAT/#367] Home un/publish api handling
  presentation/home/build.gradle.kts
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeUiState.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/navigation/HomeNavigation.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/type/DiaryCardState.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
Labels: FEAT✨, 🍀민재

#371 [REF/#370] Update token reissue endpoint and restart app
  app/build.gradle.kts
  app/src/main/java/com/hilingual/app/AppRestarterImpl.kt
  app/src/main/java/com/hilingual/di/AppModule.kt
  core/common/src/main/java/com/hilingual/core/common/app/AppRestarter.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/hilingual/core/network/AuthInterceptor.kt
  core/network/src/main/java/com/hilingual/core/network/NetworkModule.kt
  core/network/src/main/java/com/hilingual/core/network/TokenAuthenticator.kt
  data/auth/src/main/java/com/hilingual/data/auth/service/ReissueService.kt
Labels: REFACTOR🧽, 🍀민재

#374 [FEAT/#359] 피드 검색 API 연동
  data/feed/src/main/java/com/hilingual/data/feed/datasource/FeedRemoteDataSource.kt
  data/feed/src/main/java/com/hilingual/data/feed/datasourceimpl/FeedRemoteDataSourceImpl.kt
  data/feed/src/main/java/com/hilingual/data/feed/model/UserListModel.kt
  data/feed/src/main/java/com/hilingual/data/feed/repository/FeedRepository.kt
  data/feed/src/main/java/com/hilingual/data/feed/repositoryimpl/FeedRepositoryImpl.kt
  data/feed/src/main/java/com/hilingual/data/feed/service/FeedService.kt
  data/user/src/main/java/com/hilingual/data/user/datasouceimpl/UserRemoteDataSourceImpl.kt
  data/user/src/main/java/com/hilingual/data/user/datasource/UserRemoteDataSource.kt
  data/user/src/main/java/com/hilingual/data/user/repository/UserRepository.kt
  data/user/src/main/java/com/hilingual/data/user/repositoryimpl/UserRepositoryImpl.kt
  data/user/src/main/java/com/hilingual/data/user/service/UserService.kt
  presentation/feed/build.gradle.kts
  presentation/feed/src/main/java/com/hilingual/presentation/feed/model/UserSearchUiModel.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/search/FeedSearchViewModel.kt
Labels: FEAT✨, 🍀작은나현

#361 [FEAT/#350] 팔로우 화면 관련 API 연결
  data/user/src/main/java/com/hilingual/data/user/datasouceimpl/UserRemoteDataSourceImpl.kt
  data/user/src/main/java/com/hilingual/data/user/datasource/UserRemoteDataSource.kt
  data/user/src/main/java/com/hilingual/data/user/repository/UserRepository.kt
  data/user/src/main/java/com/hilingual/data/user/repositoryimpl/UserRepositoryImpl.kt
  data/user/src/main/java/com/hilingual/data/user/service/UserService.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListUiState.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListViewModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/model/FollowItemModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/model/FollowTabType.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/navigation/FeedProfileNavigation.kt
Labels: FEAT✨, 🍀큰나현

#373 [FEAT/#368] 피드 홈 ptr 적용 및 유저 관련 API 추가 연동
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/FeedCard.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/content/UserActionItem.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/image/ProfileImage.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedTabScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedUiState.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedViewModel.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/component/FeedTopAppBar.kt
  presentation/feeddiary/build.gradle.kts
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryScreen.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryViewModel.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/component/FeedDiaryProfile.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/state/MainAppState.kt
Labels: FEAT✨, 🍀작은나현

#376 [FEAT/#356] 피드 프로필 유저 액션 관련 api 연결
  presentation/feedprofile/build.gradle.kts
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/DiaryListScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileViewModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/component/FeedProfileInfo.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/AddVocaButton.kt
Labels: FEAT✨, 🍀큰나현

#403 [FIX/#399] 2차 QA 수정 사항 반영
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileViewModel.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaViewModel.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/component/VocaHeader.kt
Labels: FIX🪲, 🍀큰나현

#405 [FIX/#398] QA bug fix
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/pulltorefresh/HilingualPullToRefreshBox.kt
  core/designsystem/src/main/java/com/hilingual/core/designsystem/component/textfield/HilingualBasicTextField.kt
  data/auth/src/main/java/com/hilingual/data/auth/repositoryimpl/AuthRepositoryImpl.kt
  presentation/auth/src/main/java/com/hilingual/presentation/auth/AuthScreen.kt
  presentation/diaryfeedback/src/main/java/com/hilingual/presentation/diaryfeedback/DiaryFeedbackScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryFeedbackLoadingScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryFeedbackStatusScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/DiaryWriteScreen.kt
  presentation/diarywrite/src/main/java/com/hilingual/presentation/diarywrite/component/AnimatedLoadingLottie.kt
  presentation/diarywrite/src/main/res/raw/lottie_feedback_loading_1.json
  presentation/diarywrite/src/main/res/raw/lottie_feedback_loading_2.json
  presentation/diarywrite/src/main/res/raw/lottie_feedback_loading_3.json
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedTabScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/search/FeedSearchScreen.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryScreen.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryViewModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowListScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/follow/FollowScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/navigation/FeedProfileNavigation.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeScreen.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeUiState.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/HomeViewModel.kt
  presentation/home/src/main/java/com/hilingual/presentation/home/component/footer/DiaryTimeInfo.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/blockeduser/BlockedUserScreen.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/blockeduser/BlockedUserViewModel.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/component/MyInfoBox.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/navigation/MyPageNavigation.kt
  presentation/mypage/src/main/java/com/hilingual/presentation/mypage/profileedit/ProfileEditScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/detail/NotificationDetailScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/NotificationScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/tab/FeedScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/main/tab/NoticeScreen.kt
  presentation/notification/src/main/java/com/hilingual/presentation/notification/setting/NotificationSettingScreen.kt
  presentation/onboarding/src/main/java/com/hilingual/presentation/onboarding/OnboardingScreen.kt
  presentation/otp/src/main/java/com/hilingual/presentation/otp/OtpScreen.kt
  presentation/splash/src/main/java/com/hilingual/presentation/splash/SplashScreen.kt
  presentation/voca/src/main/java/com/hilingual/presentation/voca/VocaScreen.kt
Labels: FIX🪲, REFACTOR🧽, 🍀민재

#408 [chore/#407] Set proguard, consumer rules config
  app/proguard-rules.pro
  core/network/consumer-rules.pro
Labels: CHORE🧹, 🍀민재

#414 [CHORE/#411] 릴리즈 관련 코드 수정
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
Labels: CHORE🧹, 🍀민재

#419 [FIX/#418] 스낵바 이동시 탭 선택 수정
  app/proguard-rules.pro
  presentation/feed/src/main/java/com/hilingual/presentation/feed/FeedScreen.kt
  presentation/feed/src/main/java/com/hilingual/presentation/feed/navigation/FeedNavigation.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/FeedDiaryScreen.kt
  presentation/feeddiary/src/main/java/com/hilingual/presentation/feeddiary/navigation/FeedDiaryNavigation.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileScreen.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/FeedProfileViewModel.kt
  presentation/feedprofile/src/main/java/com/hilingual/presentation/feedprofile/profile/navigation/FeedProfileNavigation.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/MainScreen.kt
  presentation/main/src/main/java/com/hilingual/presentation/main/state/MainAppState.kt
Labels: FIX🪲, 🍀민재
